name: CI

on: [push, pull_request]

jobs:
  skip_concurrent_build:
    name: Skip Concurrent Builds
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - uses: fkirc/skip-duplicate-actions@v5.3.0
        id: skip_check
        with:
          concurrent_skipping: 'same_content'
          github_token: ${{ github.token }}
          do_not_skip: '["pull_request"]'
          cancel_others: 'true'
          skip_after_successful_duplicate: 'false'
          
  build:
    needs: skip_concurrent_build
    if: ${{ needs.skip_concurrent_build.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - 'head'
        gem: ['sunspot', 'sunspot_rails', 'sunspot_solr']
        update-format: ['xml', 'json']
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: '1'
        bundler-cache: true # 'bundle install' and cache are handled automatically
    - name: Test
      run: ci/sunspot_test_script.sh
      env:
        GEM: ${{ matrix.gem }}
        UPDATE_FORMAT: ${{ matrix.update-format }}
        RUBY_VERSION: ${{ matrix.ruby-version }}
